#!/bin/bash
set -euo pipefail

echo "🔍 Testing Nova with generated inputs..."

# Test Nova with the exact inputs generated by the script
docker run --rm \
  --cpus=1.0 \
  --memory=2g \
  --memory-swap=2g \
  -v "$(pwd)/data:/app/data" \
  -v "$(pwd)/circuits:/app/circuits" \
  -v "$(pwd)/scripts:/app/scripts" \
  -v "$(pwd)/src:/app/src" \
  -v "$(pwd)/configs:/app/configs" \
  iot-zk-snark-eval -c "
    source iot_zk_env/bin/activate
    cd /app/circuits/nova
    echo 'Testing with script-generated inputs...'
    
    # Create the exact inputs generated by the script
    echo '{\"sum\": \"0\", \"count\": \"0\"}' > init.json
    echo '[{\"values\": [\"233\", \"473\", \"0\", \"1983\", \"214\", \"561\", \"0\", \"0\", \"283\", \"645\"], \"batch_id\": \"1\"}]' > steps.json
    
    echo 'Input files:'
    cat init.json
    echo ''
    cat steps.json
    echo ''
    
    echo 'Trying Nova prove...'
    zokrates nova prove
    echo 'Nova prove successful!'
    
    echo 'Trying Nova compress...'
    zokrates nova compress
    echo 'Nova compress successful!'
    
    echo 'Trying Nova verify...'
    zokrates nova verify
    echo 'Nova verify successful!'
  "

echo "✅ Test completed!"
